/** Demo 15U clubs so a director can fill a 40-team field and then cut it down. */
export const DEMO_TEAM_NAMES = [
  "Athens Aces",
  "Calhoun Crushers",
  "Chattanooga Canes",
  "Cleveland Cardinals",
  "Cookeville Prime",
  "Dalton Dynasty",
  "Dayton Dirtbags",
  "East TN Elite",
  "Etowah Eagles",
  "Farragut Force",
  "Franklin Phenom",
  "Hixson Hawks",
  "Jefferson City Jets",
  "Knoxville Knights",
  "Lenoir City Lightning",
  "Loudon Outlaws",
  "Madisonville Mavericks",
  "Maryville Mustangs",
  "McMinn Select",
  "Meigs County Heat",
  "Morristown Storm",
  "Oak Ridge Rangers",
  "Ooltewah Impact",
  "Powell Prospects",
  "Riceville Rebels",
  "Sevierville Showcase",
  "Signal Mountain Wolves",
  "Sweetwater Bandits",
  "Tellico Titans",
  "Vonore Venom",
  "Westside Warriors",
  "White Pine Wildcats",
  "Cleveland Bombers",
  "Athens Thunder",
  "Chatt Nation",
  "Knox Elite",
  "Tri-Cities Aces",
  "Smoky Mountain Select",
  "Hiwassee Hawks",
  "Copper Basin Crush",
] as const;

export const DEMO_PARKS: { name: string; address: string }[] = [
  { name: "Tennessee Wesleyan Diamond", address: "204 E College Street, Athens, TN" },
  { name: "Athens Regional Park", address: "1001 N Jackson Street, Athens, TN" },
  { name: "Calhoun Community Park", address: "200 Park Street, Calhoun, TN" },
  { name: "Etowah City Park", address: "600 Tennessee Avenue, Etowah, TN" },
  { name: "Englewood Ball Fields", address: "12 Church Street, Englewood, TN" },
  { name: "Riceville Recreation Park", address: "150 County Road 60, Riceville, TN" },
];
