/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as WeekendsRouteImport } from './routes/weekends'
import { Route as BracketWeekendIdRouteImport } from './routes/bracket.$weekendId'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as TeamsNewRouteImport } from './routes/teams.new'
import { Route as WeekendsIndexRouteImport } from './routes/weekends.index'
import { Route as WeekendsWeekendIdRouteImport } from './routes/weekends.$weekendId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WeekendsWeekendIdIndexRouteImport } from './routes/weekends.$weekendId.index'
import { Route as WeekendsWeekendIdEditRouteImport } from './routes/weekends.$weekendId.edit'
import { Route as WeekendsWeekendIdLocationsRouteImport } from './routes/weekends.$weekendId.locations'
import { Route as WeekendsWeekendIdRulesRouteImport } from './routes/weekends.$weekendId.rules'
import { Route as WeekendsWeekendIdTeamsRouteImport } from './routes/weekends.$weekendId.teams'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendsRoute = WeekendsRouteImport.update({
  id: '/weekends',
  path: '/weekends',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketWeekendIdRoute = BracketWeekendIdRouteImport.update({
  id: '/bracket/$weekendId',
  path: '/bracket/$weekendId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRoute,
} as any)
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TeamsRoute,
} as any)
const WeekendsIndexRoute = WeekendsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeekendsRoute,
} as any)
const WeekendsWeekendIdRoute = WeekendsWeekendIdRouteImport.update({
  id: '/$weekendId',
  path: '/$weekendId',
  getParentRoute: () => WeekendsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendsWeekendIdIndexRoute = WeekendsWeekendIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeekendsWeekendIdRoute,
} as any)
const WeekendsWeekendIdEditRoute = WeekendsWeekendIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => WeekendsWeekendIdRoute,
} as any)
const WeekendsWeekendIdLocationsRoute =
  WeekendsWeekendIdLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => WeekendsWeekendIdRoute,
  } as any)
const WeekendsWeekendIdRulesRoute = WeekendsWeekendIdRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => WeekendsWeekendIdRoute,
} as any)
const WeekendsWeekendIdTeamsRoute = WeekendsWeekendIdTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => WeekendsWeekendIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/teams': typeof TeamsRouteWithChildren
  '/weekends': typeof WeekendsRouteWithChildren
  '/bracket/$weekendId': typeof BracketWeekendIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/weekends/$weekendId': typeof WeekendsWeekendIdRouteWithChildren
  '/teams/': typeof TeamsIndexRoute
  '/weekends/': typeof WeekendsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/weekends/$weekendId/edit': typeof WeekendsWeekendIdEditRoute
  '/weekends/$weekendId/locations': typeof WeekendsWeekendIdLocationsRoute
  '/weekends/$weekendId/rules': typeof WeekendsWeekendIdRulesRoute
  '/weekends/$weekendId/teams': typeof WeekendsWeekendIdTeamsRoute
  '/weekends/$weekendId/': typeof WeekendsWeekendIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/bracket/$weekendId': typeof BracketWeekendIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/teams': typeof TeamsIndexRoute
  '/weekends': typeof WeekendsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/weekends/$weekendId/edit': typeof WeekendsWeekendIdEditRoute
  '/weekends/$weekendId/locations': typeof WeekendsWeekendIdLocationsRoute
  '/weekends/$weekendId/rules': typeof WeekendsWeekendIdRulesRoute
  '/weekends/$weekendId/teams': typeof WeekendsWeekendIdTeamsRoute
  '/weekends/$weekendId': typeof WeekendsWeekendIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/teams': typeof TeamsRouteWithChildren
  '/weekends': typeof WeekendsRouteWithChildren
  '/bracket/$weekendId': typeof BracketWeekendIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/weekends/$weekendId': typeof WeekendsWeekendIdRouteWithChildren
  '/teams/': typeof TeamsIndexRoute
  '/weekends/': typeof WeekendsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/weekends/$weekendId/edit': typeof WeekendsWeekendIdEditRoute
  '/weekends/$weekendId/locations': typeof WeekendsWeekendIdLocationsRoute
  '/weekends/$weekendId/rules': typeof WeekendsWeekendIdRulesRoute
  '/weekends/$weekendId/teams': typeof WeekendsWeekendIdTeamsRoute
  '/weekends/$weekendId/': typeof WeekendsWeekendIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/join'
    | '/login'
    | '/notifications'
    | '/resources'
    | '/schedule'
    | '/teams'
    | '/weekends'
    | '/bracket/$weekendId'
    | '/teams/$teamId'
    | '/teams/new'
    | '/weekends/$weekendId'
    | '/teams/'
    | '/weekends/'
    | '/api/auth/$'
    | '/weekends/$weekendId/edit'
    | '/weekends/$weekendId/locations'
    | '/weekends/$weekendId/rules'
    | '/weekends/$weekendId/teams'
    | '/weekends/$weekendId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/join'
    | '/login'
    | '/notifications'
    | '/resources'
    | '/schedule'
    | '/bracket/$weekendId'
    | '/teams/$teamId'
    | '/teams/new'
    | '/teams'
    | '/weekends'
    | '/api/auth/$'
    | '/weekends/$weekendId/edit'
    | '/weekends/$weekendId/locations'
    | '/weekends/$weekendId/rules'
    | '/weekends/$weekendId/teams'
    | '/weekends/$weekendId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/join'
    | '/login'
    | '/notifications'
    | '/resources'
    | '/schedule'
    | '/teams'
    | '/weekends'
    | '/bracket/$weekendId'
    | '/teams/$teamId'
    | '/teams/new'
    | '/weekends/$weekendId'
    | '/teams/'
    | '/weekends/'
    | '/api/auth/$'
    | '/weekends/$weekendId/edit'
    | '/weekends/$weekendId/locations'
    | '/weekends/$weekendId/rules'
    | '/weekends/$weekendId/teams'
    | '/weekends/$weekendId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ResourcesRoute: typeof ResourcesRoute
  ScheduleRoute: typeof ScheduleRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  WeekendsRoute: typeof WeekendsRouteWithChildren
  BracketWeekendIdRoute: typeof BracketWeekendIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekends': {
      id: '/weekends'
      path: '/weekends'
      fullPath: '/weekends'
      preLoaderRoute: typeof WeekendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bracket/$weekendId': {
      id: '/bracket/$weekendId'
      path: '/bracket/$weekendId'
      fullPath: '/bracket/$weekendId'
      preLoaderRoute: typeof BracketWeekendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/weekends/': {
      id: '/weekends/'
      path: '/'
      fullPath: '/weekends/'
      preLoaderRoute: typeof WeekendsIndexRouteImport
      parentRoute: typeof WeekendsRoute
    }
    '/weekends/$weekendId': {
      id: '/weekends/$weekendId'
      path: '/$weekendId'
      fullPath: '/weekends/$weekendId'
      preLoaderRoute: typeof WeekendsWeekendIdRouteImport
      parentRoute: typeof WeekendsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekends/$weekendId/': {
      id: '/weekends/$weekendId/'
      path: '/'
      fullPath: '/weekends/$weekendId/'
      preLoaderRoute: typeof WeekendsWeekendIdIndexRouteImport
      parentRoute: typeof WeekendsWeekendIdRoute
    }
    '/weekends/$weekendId/edit': {
      id: '/weekends/$weekendId/edit'
      path: '/edit'
      fullPath: '/weekends/$weekendId/edit'
      preLoaderRoute: typeof WeekendsWeekendIdEditRouteImport
      parentRoute: typeof WeekendsWeekendIdRoute
    }
    '/weekends/$weekendId/locations': {
      id: '/weekends/$weekendId/locations'
      path: '/locations'
      fullPath: '/weekends/$weekendId/locations'
      preLoaderRoute: typeof WeekendsWeekendIdLocationsRouteImport
      parentRoute: typeof WeekendsWeekendIdRoute
    }
    '/weekends/$weekendId/rules': {
      id: '/weekends/$weekendId/rules'
      path: '/rules'
      fullPath: '/weekends/$weekendId/rules'
      preLoaderRoute: typeof WeekendsWeekendIdRulesRouteImport
      parentRoute: typeof WeekendsWeekendIdRoute
    }
    '/weekends/$weekendId/teams': {
      id: '/weekends/$weekendId/teams'
      path: '/teams'
      fullPath: '/weekends/$weekendId/teams'
      preLoaderRoute: typeof WeekendsWeekendIdTeamsRouteImport
      parentRoute: typeof WeekendsWeekendIdRoute
    }
  }
}

interface TeamsRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  TeamsNewRoute: typeof TeamsNewRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  TeamsNewRoute: TeamsNewRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface WeekendsWeekendIdRouteChildren {
  WeekendsWeekendIdEditRoute: typeof WeekendsWeekendIdEditRoute
  WeekendsWeekendIdLocationsRoute: typeof WeekendsWeekendIdLocationsRoute
  WeekendsWeekendIdRulesRoute: typeof WeekendsWeekendIdRulesRoute
  WeekendsWeekendIdTeamsRoute: typeof WeekendsWeekendIdTeamsRoute
  WeekendsWeekendIdIndexRoute: typeof WeekendsWeekendIdIndexRoute
}

const WeekendsWeekendIdRouteChildren: WeekendsWeekendIdRouteChildren = {
  WeekendsWeekendIdEditRoute: WeekendsWeekendIdEditRoute,
  WeekendsWeekendIdLocationsRoute: WeekendsWeekendIdLocationsRoute,
  WeekendsWeekendIdRulesRoute: WeekendsWeekendIdRulesRoute,
  WeekendsWeekendIdTeamsRoute: WeekendsWeekendIdTeamsRoute,
  WeekendsWeekendIdIndexRoute: WeekendsWeekendIdIndexRoute,
}

const WeekendsWeekendIdRouteWithChildren =
  WeekendsWeekendIdRoute._addFileChildren(WeekendsWeekendIdRouteChildren)

interface WeekendsRouteChildren {
  WeekendsWeekendIdRoute: typeof WeekendsWeekendIdRouteWithChildren
  WeekendsIndexRoute: typeof WeekendsIndexRoute
}

const WeekendsRouteChildren: WeekendsRouteChildren = {
  WeekendsWeekendIdRoute: WeekendsWeekendIdRouteWithChildren,
  WeekendsIndexRoute: WeekendsIndexRoute,
}

const WeekendsRouteWithChildren = WeekendsRoute._addFileChildren(
  WeekendsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ResourcesRoute: ResourcesRoute,
  ScheduleRoute: ScheduleRoute,
  TeamsRoute: TeamsRouteWithChildren,
  WeekendsRoute: WeekendsRouteWithChildren,
  BracketWeekendIdRoute: BracketWeekendIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
